Better logging – everywhere. Simplification of how app.config is used
godaddy/carpenterd pull request #23
Opened 2017-08-17 08:55 UTC by indexzero

- [api] Better logging around file purging.
- [refactor] Remove additional calls to `app.config.get('builder')` since that is passed in the preboot.
- [refactor] Setup additional state in the constructor instead of on each build.
- [refactor] Move private methods to the bottom of files.
- [refactor] Rename outputPath to installPath.
- [refactor api] Pass opts and args to `./lib/constructor/npm/index.js`.
- [api] Use opts passed to npm to specify log files for `stdout.log` and `stderr.log`.
- [api] Slightly increase the magic number of additional built-in retries before purging.
- [refactor] Move fitting code into `lib/constructor/fitting.js`.

The `stdout.log` and `stderr.log` files generated are guaranteed to be cleaned up along with the other build files when it is complete. While in process, however, they represent a tailable source of debugging.

2017-08-17 17:17 UTC, bmeck approved these changes

2017-08-17 17:17 UTC, bmeck commented on lib/constructor/npm/index.js
>  const bl = require('bl');
nit: unused require now

2017-08-17 17:55 UTC, jcrugzz requested changes
Looks good overall. just needs some linting fixes and some error handlers.

2017-08-17 17:55 UTC, jcrugzz commented on lib/constructor/npm/index.js
> +  child.stderr.pipe(fs.createWriteStream(logs.stderr));
these need error handlers or they could throw

2017-08-17 17:55 UTC, jcrugzz commented on lib/constructor/npm/index.js
> +  child.stdout.pipe(fs.createWriteStream(logs.stdout));
same as above

2017-08-17 17:55 UTC, jcrugzz commented on lib/constructor/index.js
> +  const pkgDir = path.join(installPath, 'package');
not needed anymore

2017-08-17 17:55 UTC, jcrugzz commented on lib/constructor/index.js
> +  app.contextLog.info('Create paths mkdirp: %s', spec.name, spec);
do we need both of these logs?

2017-08-17 17:55 UTC, jcrugzz commented on lib/constructor/fitting.js
> +  const match = '';
`let`

2017-08-18 01:20 UTC, jcrugzz approved these changes

2017-08-18 02:15 UTC, indexzero commented on lib/constructor/index.js
> +  const pkgDir = path.join(installPath, 'package');
It gets used below:

``` js
pack: this.pack.bind(this, pkgDir, tarball),
```

2017-08-18 17:49 UTC, merged