[fix] keep track of build failures for a given build
godaddy/carpenterd pull request #28
Opened 2017-08-25 16:38 UTC by jcrugzz

2017-08-25 18:29 UTC, decompil3d requested changes

2017-08-25 18:29 UTC, decompil3d commented on lib/constructor/index.js
> +  this.maxFailures = options.maxFailures app.config.get('maxFailures') || 2;
Missing a `||`?

2017-08-25 19:08 UTC, decompil3d approved these changes

2017-08-31 00:18 UTC, indexzero approved these changes

2017-08-31 03:49 UTC, merged