Send messages to NSQ to support the status api
godaddy/carpenterd pull request #34
Opened 2018-06-05 17:19 UTC by msluther

Sending along various payloads to a new NSQ topic that will be consumed by the warehouse.ai status API.  These payloads include chatty `event` messages that describe whats going on internally, and also `queued`, `ignored`, & `error` events that will more directly affect the status api.

2018-06-05 17:20 UTC, msluther commented
Travis failure is `node@6` only and due to usage of the spread operator in the test code.  Will submit a fix.

2018-06-05 19:01 UTC, jcrugzz requested changes
This seems good, id just also like to see some documentation of the status data-structures, especially with defining the various `eventType`s which will be necessary for the status-api to understand. This will then feed into the status-api docs.

2018-06-05 19:01 UTC, jcrugzz commented on lib/construct/progress.js
> +    message: JSON.stringify(data)
I feel this message should be human readable and be a meaningful description that a consumer could grok.

2018-06-05 19:02 UTC, jcrugzz commented
As I also mentioned to you in chat, we can allow failures for node@10 for now using the .travis.yml config https://github.com/winstonjs/winston/blob/master/.travis.yml#L16-L18.

2018-06-05 19:07 UTC, jcrugzz requested changes
Another note I want to make @msluther is I think we should send some events around the `npm install` bit which currently doesn't have access to the progress stream. I think its worth the slight refactor to be able to indicate status before `npm install` and after to indicate specific success/failures around that.

2018-06-05 19:32 UTC, msluther commented on lib/construct/progress.js
> +    message: JSON.stringify(data)
Fair point.  data.message seems like the right thing here, its already intentionally human readable, but i'll include data.progress as well and interpolate them.

2018-06-06 01:49 UTC, jcrugzz approved these changes

2018-06-06 01:52 UTC, jcrugzz commented on lib/construct/progress.js
> +  if (typeof (data) === 'string') {
no need for parens after `typeof`

2018-06-06 18:05 UTC, merged

2018-06-07 19:44 UTC, indexzero commented
Post humous 👍 💯 ... nice work @msluther! <3