[fix] harmless change to help indicate to feedsme it was a publish
godaddy/carpenterd pull request #36
Opened 2018-10-17 22:53 UTC by jcrugzz

We want to differentiate between a `dist-tag` command from a distinct publish since the actions taken would be different in feedsme.

2018-10-18 17:04 UTC, msluther requested changes
Probably worth having a test since it's crucial knowledge now for feedsme.

2018-10-19 18:19 UTC, fritzmonkey approved these changes

2018-10-19 18:19 UTC, fritzmonkey commented on test/lib/routes/index.test.js
> +          assume(feedStub).is.calledWithMatch('dev', sinon.match.has('data', sinon.match.has('__published', true)), sinon.match.func);
```suggestion
          assume(feedStub).is.calledWithMatch('dev', sinon.match.hasNested('data.__published', true), sinon.match.func);
```
Nit, but `hasNested` is a little more succinct.

2018-10-22 15:29 UTC, msluther approved these changes

2018-10-23 13:32 UTC, merged