Modernize a few of the files
godaddy/carpenterd pull request #40
Opened 2019-02-27 19:39 UTC by SivanMehta

> convert it to a `class`, arrow functions and using `this` over `constructor`, and think about if you want to do the async await conversion or if getting your hands dirty enough

2019-02-27 22:33 UTC, jcrugzz requested changes

2019-02-27 22:33 UTC, jcrugzz commented on lib/construct/index.js
> +    EventEmitter.call(this, options);
is this needed given the `super()` call? It should be equivalent. you could pass `options` though

2019-02-27 22:33 UTC, jcrugzz commented on lib/construct/index.js
> +    require('emits')(...arguments);
do we actually use this anywhere explicitly?

2019-02-27 22:37 UTC, SivanMehta commented on lib/construct/index.js
> +    require('emits')(...arguments);
I'm not sure about in this repo. This function serves to replace the original prototype declaration [here](https://github.com/godaddy/carpenterd/blob/master/lib/construct/index.js#L98
)

```js
Constructor.prototype.emits = require('emits');
```

2019-02-27 22:42 UTC, 3rd-Eden requested changes

2019-02-27 22:42 UTC, 3rd-Eden commented on lib/app.js
> -'use strict';
The `use strict` should be kept for Node.js

2019-02-27 22:42 UTC, 3rd-Eden commented on lib/app.js
> -'use strict';
related: https://twitter.com/matteocollina/status/1100468412701126656

2019-02-27 22:52 UTC, jcrugzz commented on lib/construct/index.js
> +    require('emits')(...arguments);
@SivanMehta understood, id just verify that its used otherwise remove altogether

2019-02-27 23:23 UTC, jcrugzz approved these changes

2019-02-28 00:22 UTC, 3rd-Eden commented on lib/construct/index.js
> +    require('emits')(...arguments);
Yeah, let's not call `require` every time this function is called as `require` is a **sync** operation which will freeze the event loop. I would suggest doing a `const emits = require('emits')` and doing a `this.emits = emits` in the `constructor` to restore the original functionality .

2019-03-01 16:30 UTC, 3rd-Eden approved these changes

2019-03-01 17:26 UTC, merged