Use async/await
godaddy/carpenterd pull request #42
Opened 2019-03-06 00:15 UTC by SivanMehta

In preparation for consuming `@wrhs/extract-config` and `workers-factory@1.7.4`

- [ ] `async/await` conversion of (most of) `lib/construct/index.js`
- [x] Make sure the tests still pass so ensure functional parity.

2019-03-14 16:54 UTC, jcrugzz requested changes
Couple nits but otherwise this looks good

2019-03-14 16:54 UTC, jcrugzz commented on lib/construct/index.js
> +        return next(err);
lets just return the paths and get rid of the callback. Throw if there's an error and catch it to check if its `err.install` etc. So we aren't mixing promises and callbacks

2019-03-14 16:54 UTC, jcrugzz commented on lib/construct/builder.js
> +class Builder {
this seems like a duplicate of cleaner?

2019-03-14 16:56 UTC, SivanMehta commented on lib/construct/builder.js
> +class Builder {
yep it is. Forgot to delete it

2019-03-14 17:12 UTC, SivanMehta commented on lib/construct/index.js
> +        return next(err);
donezo

2019-03-14 19:29 UTC, SivanMehta commented on lib/construct/builder.js
> +class Builder {
nevermind it's back in a new form

2019-03-15 15:50 UTC, jcrugzz approved these changes
Overall this looks good @SivanMehta. Do you want to merge this PR and then do the follow up refactor to integrate `@wrhs/extract-config`?

2019-03-15 15:59 UTC, merged